### ISSUE TITLE
Removed Records: Shared formula from /xl/worksheets/sheet1.xml part error

### ISSUE THREAD

**Issue by Romeo84095** [nissl-lab/npoi-examples#1]
Hi. I have Excel sheet like this

```
A         B         C
1         2          =A1*B1
2         2          =A2*B2
3         2          =A2*B3
```

After i open this file in NPOI 2.5.2 and try to replace formula with just text (for example in C2 cell) i save it. When i open it with MS Excel i got the following error "Removed Records: Shared formula from /xl/worksheets/sheet1.xml"
"Removed Records: Formula from /xl/calcChain.xml part (Calculation properties)".

Here my code

```
void Test02()
        {
            using (System.IO.FileStream fsIn = new System.IO.FileStream("SourceExcel.xlsx", System.IO.FileMode.Open, System.IO.FileAccess.Read))
            {
                // Open simple sheet
                NPOI.XSSF.UserModel.XSSFWorkbook xBookIn = new NPOI.XSSF.UserModel.XSSFWorkbook(fsIn);
                var xSheetIn = xBookIn.GetSheetAt(0);

                xSheetIn.GetRow(2).CreateCell(2); xSheetIn.GetRow(2).GetCell(2).SetCellValue("justNewCell");


                var fsOut = new System.IO.FileStream("ResultedExcel.xlsx", System.IO.FileMode.Create);
                xBookIn.Write(fsOut, false);
            }
        }
```

I am also attaching source and destination file (with error). Thanks.
[ResultedExcel.xlsx](https://github.com/nissl-lab/npoi-examples/files/5865747/ResultedExcel.xlsx)
[SourceExcel.xlsx](https://github.com/nissl-lab/npoi-examples/files/5865748/SourceExcel.xlsx)

**Comment by tonyqus** [comment]
It's not necessary to Create C2 cell again while it has been there. Try to call GetCell for the C2 cell directly and see if you can reproduce the issue

**Comment by Romeo84095** [comment]
When i tried just change cell value via (and not creating new cell)
`xSheetIn.GetRow(2).GetCell(2).SetCellValue("test2");`
it worked ok, without any error.

But if i tried to clear cell via following code
`xSheetIn.GetRow(2).GetCell(2).SetCellType(NPOI.SS.UserModel.CellType.Blank);`
i have the same error
```
Removed Records: Shared formula from /xl/worksheets/sheet1.xml part
Removed Records: Formula from /xl/calcChain.xml part (Calculation properties)
```

**Comment by Romeo84095** [comment]
And when i try to change cell type to string and set value via the following code
```
xSheetIn.GetRow(2).GetCell(2).SetCellType(NPOI.SS.UserModel.CellType.String);
xSheetIn.GetRow(2).GetCell(2).SetCellValue("test2");
```

i had same error. See full MS Excel log

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<recoveryLog xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><logFileName>error346600_01.xml</logFileName><summary>Errors were detected in file 'C:\Users\eshmrom\Documents\_Projects\_TestingTemplatesExamples\TestNpoiError20201112\TestNpoiError20201112\bin\Debug\ResultedExcel.xlsx'</summary><removedRecords><removedRecord>Removed Records: Shared formula from /xl/worksheets/sheet1.xml part</removedRecord><removedRecord>Removed Records: Formula from /xl/calcChain.xml part (Calculation properties)</removedRecord></removedRecords></recoveryLog>
```

**Comment by tonyqus** [comment]
> `xSheetIn.GetRow(2).GetCell(2).SetCellType(NPOI.SS.UserModel.CellType.Blank);`

To clean a cell,  please call ICell.RemoveCell directly. Manually set cell type to blank is not the correct way.

**Comment by Romeo84095** [comment]
Hi. I tried to use ICell.RemoveCell directly, but ICell interface hasn’t RemoveCell method. Then i tried just delete cell with formula by using xSheetIn.GetRow(2).RemoveCell(xSheetIn.GetRow(2).GetCell(2))
But after it when i opened it in Ms Excel i had exactly the same error(

Is it related to Excel shared formulas or calculation chain?
