### ISSUE TITLE
Does workbook loads whole data into memory ?

### ISSUE THREAD

**Issue by graysuit** [nissl-lab/npoi-examples#12]
I'm having time problems while writing XSLX files.
Suppose I create X number of columns with Y number of rows. Will all be done in memory ?
Then what will happen if data I wanted to write is more than GBs. I expect it to crash.

Do you support streaming ? 
like create 1 row and append to XSLX, 
then create 1 row and append to XSLX
....
```csharp
            IWorkbook workbook = new XSSFWorkbook();
            ISheet sheet1 = workbook.CreateSheet("Sheet1");
            sheet1.CreateRow(0).CreateCell(0).SetCellValue("This is a Sample");
            int x = 1;

            Console.WriteLine("Start at " + DateTime.Now.ToString());
            for (int i = 1; i <= 70000; i++)
            {
                IRow row = sheet1.CreateRow(i);
                for (int j = 0; j < 15; j++)
                {
                    row.CreateCell(j).SetCellValue(x++);
                }
            }
            Console.WriteLine("End at " + DateTime.Now.ToString());

            FileStream sw = File.Create("test.xlsx");

           //Looks like workbook loads all data into memory. lol
            workbook.Write(sw);
           //Looks like workbook loads all data into memory. lol
           
            sw.Close();
```
By this way, it doesn't matter how much data is. And will performance friendly.
do you have any advise on this or any way I can walk through ?

Regards

**Comment by tonyqus** [comment]
Streaming is not a option for any Excel file since the file formats is not designed for that. 

A few users like testing huge data cases. But are you sure Excel is suitable for your case? How about csv or parquet file?
