### ISSUE TITLE
Make Examples Output UTF-8

### ISSUE THREAD

**Issue by theonewolf** [nissl-lab/npoi-examples#18]
@tonyqus I think your examples are *excellent*.  I noticed you even put character in them that require a large character set interpretation (not just ASCII).

I think your examples would be more powerful if you added a line like this (especially the `ReadAndPrintData` example):

```C#
            Console.OutputEncoding = System.Text.Encoding.UTF8;
```

**Comment by tonyqus** [comment]
Your suggestion makes sense. I'll change the examples.
