### ISSUE TITLE
How to Remove Row without issues? 

### ISSUE THREAD

**Issue by Kriof** [nissl-lab/npoi-examples#19]
Hi,
I;m trying to RemoveRow using

     sheet.RemoveRow(row);   // this only deletes all the cell values

            int rowIndex = row.RowNum;

            int lastRowNum = sheet.LastRowNum;

            if (rowIndex >= 0 && rowIndex < lastRowNum)
            {
                sheet.ShiftRows(rowIndex + 1, lastRowNum, -1);
            }

Above solution causes some issues:
- Index out of range on some cells with values 
- Excel file after opening have pre-selected last row and column(Despite it's empty)

How can i remove rows without complications

**Comment by tonyqus** [comment]
Can you upload an example Excel file that will cause Index out of range?
