### ISSUE TITLE
Which VS to use? 2017, 2019 or any? Just complains about nuget packages

### ISSUE THREAD

**Issue by mattiasw2** [nissl-lab/npoi-examples#2]
`Could not resolve this reference. Could not locate the assembly "NPOI, Version=2.5.2.0, Culture=neutral, PublicKeyToken=0df73ec7942b34e1". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.	UseBasicFormula		`	

I have tried several projects.

**Comment by tonyqus** [comment]
VS 2019 is recommended. But I'm afraid your problem is caused by .NET framework installed. Please check which .NET framework are you using in your VS.

**Comment by mattiasw2** [comment]
Installed 4.5.1 using https://dotnet.microsoft.com/download/dotnet-framework/thank-you/net451-developer-pack-offline-installer

Then reopened solution, then removed and added npoi, and then it worked. Thanks!

After looking at the diffs, it seems that the projects depends (or at least prefer) that npoi is compiled on the same machine. However, since I only interested in dotnet core, I had compile npoi for dotnetcore 3.1. The reason is that the normal generic compilation of NPOI using for all targets like standard2.0 was useless for browsing inside VS2019.
