### ISSUE TITLE
Hi ~ I need to use npoi to create a line chart in Excel. Which example should I refer to?

### ISSUE THREAD

**Issue by weiai-weiai** [nissl-lab/npoi-examples#20]
Hi ~ I need to use npoi to create a line chart in Excel. Which example should I refer to?

**Comment by weiai-weiai** [comment]
我需要使用npoi在Excel中创建折线图。我应该参考哪个例子？抱歉我的英文不好，我只能使用翻译工具来进行沟通

**Comment by tonyqus** [comment]
参考这个
https://github.com/nissl-lab/npoi-examples/tree/main/xssf/LineChart
