### ISSUE TITLE
Provide a way to add bodyElement

### ISSUE THREAD

**Issue by Guo-yupo** [nissl-lab/npoi-examples#21]
Why is there a method to delete removenodyelement. There is no way to add bodyelement？

**Comment by tonyqus** [comment]
which example are you talking about? xlsx or docx?

**Comment by Guo-yupo** [comment]
> 你在说哪个例子？xlsx 还是 docx？

npoi operation word

**Comment by Guo-yupo** [comment]
> 你在说哪个例子？xlsx 还是 docx？

docx

**Comment by tonyqus** [comment]
What kind of feature are you going to implement by bodyelement? Please clarify

**Comment by Guo-yupo** [comment]
> 你打算通过 bodyelement 实现什么样的功能？请说清楚

I want to add a new bodyelement in the specified position in the docx file, which can be a paragraph, picture or table

**Comment by Guo-yupo** [comment]
How can I judge whether a paragraph in a docx document is text or picture？
