### ISSUE TITLE
XWPF SetText() examples misleading

### ISSUE THREAD

**Issue by dstringvc** [nissl-lab/npoi-examples#25]
Many of the XWPF examples show calling run.SetText() multiple times on the same run. From these examples, I would expect this usage to append text to the run. But, calling SetText() actually replaces the text in the run. I believe the examples should use run.AppendText() on the second and successive calls.

**Comment by tonyqus** [comment]
Which example? I'd like to review the code. Perhaps it's a mistake

**Comment by dstringvc** [comment]
Likely just an oversight. The first example I found was:
1) SimpleDocument, program.cs, r4.SetText() appears on line 67 and again on line 73, each with different text; r5.SetText() appears on lines 84, 86, 90, and 94, again, all with different text

As I was looking for additional examples, I realized that I was mistaken. For example, in CreateHighlightRun, I thought SetText() was being called multiple times on the same XWPFRun instance (program.cs, lines 25, 27, and 29). I missed where the local variable was being assigned a new XWPFRun on lines 26 and 30. So, the problem is not as bad as I first thought.

I love the NPOI library and have already used it successfully to create XLSX files. I've only just started using it to create DOCX files. Please let me know if I can help out.
