### ISSUE TITLE
Excel want's to repair workbook with two sheets and two tables

### ISSUE THREAD

**Issue by PeteDurst** [nissl-lab/npoi-examples#32]
Hi everyone,

using @tonyqus example ([xssf/CreateTableInXlsx/Program.cs](https://github.com/nissl-lab/npoi-examples/tree/main/xssf/CreateTableInXlsx)) changing it to create two sheets with two tables i am getting the following excel repair message complaining about the tables/parts:
<img width="443" alt="image" src="https://github.com/nissl-lab/npoi-examples/assets/23376376/bd53b732-c374-4c58-89a9-9ff89d1ba794">

Tried @tonyqus example without changing it produces no errors. 
As soon as i add the second sheet with the second table it has to be repaired.

Thanks for any advice on this. 
Best regards,
Peter

Minimal changes to the example:

```
using NPOI.XSSF.UserModel;

namespace npoiTest
{
    internal class Program
    {
        static void Main(string[] args)
        {
            using (var workbook = new XSSFWorkbook())
            {
                CreateSheetWithTable(workbook, 1);
                CreateSheetWithTable(workbook, 2);

                using (FileStream sw = File.Create("test.xlsx"))
                {
                    workbook.Write(sw, false);
                }
            }
        }

        private static void CreateSheetWithTable(XSSFWorkbook workbook, uint i)
        {
            var sheet = (XSSFSheet)workbook.CreateSheet("Sheet" + i);
            //create the table in sheet
            var table = sheet.CreateTable();
            table.Name = "Test" + i;
            var ctTable = table.GetCTTable();
            ctTable.id = 1;
            table.IsHasTotalsRow = false;
            table.DisplayName = "Table" + i;
            table.SetCellReferences(new NPOI.SS.Util.AreaReference("A1:C5", NPOI.SS.SpreadsheetVersion.EXCEL2007));

            //CreateColumn method is available since NPOI 2.6.0
            table.CreateColumn(null, 0);
            table.CreateColumn(null, 1);
            table.CreateColumn(null, 2);
            table.StyleName = XSSFBuiltinTableStyleEnum.TableStyleMedium27.ToString();


            table.Style.IsShowColumnStripes = false;
            table.Style.IsShowRowStripes = true;

            //fill in the data
            for (int r = 0; r < 5; r++)
            {
                var row = sheet.CreateRow(r);
                for (int c = 0; c < 3; c++)
                {
                    var cell = row.CreateCell(c);
                    if (r == 0)
                    { //first row is for column headers
                        cell.SetCellValue("Column" + (c + 1)); //content **must** be here for table column names
                    }
                    else
                    {
                        cell.SetCellValue($"R{r + 1}C{c + 1}");
                    }
                }
            }
        }
    }
}
```

**Comment by PeteDurst** [comment]
Hello,

I have found the problem with the changed example. I forgot to change the `ctTable.id` to `i`.
Now the example works. 
In my code the id was set correctly.
After further testing I identified my values for `table.name` as the problem. 
Some started with _ some with numbers.
Does anyone know the rules for `table.Name`? 

I think if the question is answered, the issue can be closed. 

Best regards,
Peter

**Comment by tonyqus** [comment]
https://learn.microsoft.com/en-us/dotnet/api/documentformat.openxml.spreadsheet.table?view=openxml-3.0.1

> name (Name) 
> A string representing the name of the table that is used to reference the table programmatically through the spreadsheet applications object model. This string shall be unique per table per sheet. It has the same length and character restrictions as for displayName.By default this should be the same as the table's displayName. This name should also be kept in synch with the displayName when the displayName is updated in the UI by the spreadsheet user.The possible values for this attribute are defined by the ST_Xstring simple type (§22.9.2.19).
>
