### ISSUE TITLE
Unable To Comiple Project

### ISSUE THREAD

**Issue by asushil** [nissl-lab/npoi-examples#5]
Severity	Code	Description	Project	File	Line	Suppression State
Error		NuGet Package restore failed for project Naos.FileStorage.Rest: Unable to find version '1.0.20.6742' of package 'Architecture.IO'.
  C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\: Package 'Architecture.IO.1.0.20.6742' is not found on source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\'.
  https://api.nuget.org/v3/index.json: Package 'Architecture.IO.1.0.20.6742' is not found on source 'https://api.nuget.org/v3/index.json'.
. Please see Error List window for detailed warnings and errors.

**Comment by tonyqus** [comment]
Are you sure this is a issue belonging to NPOI? I have no idea what Architecture.IO is
