### ISSUE TITLE
Read xlsx file example ?

### ISSUE THREAD

**Issue by graysuit** [nissl-lab/npoi-examples#7]
All examples under `\xssf` seems to be writing excel files.
Do you have any sample showing how to read data from an xlsx file ?

And again, congrats for making fast excel file writer.
It saved my a lot time.
Its far better than the lib that excel sdk provide.

**Comment by tonyqus** [comment]
Yes, I agree with you. I'll add a few examples of reading data.

**Comment by graysuit** [comment]
Nice to hear that.
Thank you much. Cheers !

**Comment by tonyqus** [comment]
I suggest you take a look at the following cs file: 
https://github.com/tonyqus/toxy/blob/master/ToxyFramework/Parsers/Spreadsheet/ExcelSpreadsheetParser.cs

**Comment by graysuit** [comment]
Hi Thanks alot.
Can you please point out which line is ideal for reading a specific cell at specific row ?

**Comment by tonyqus** [comment]
https://github.com/nissl-lab/npoi-examples/blob/main/ss/ReadAndPrintData/Program.cs

**Comment by graysuit** [comment]
Done. I tested the example and it work fine.
Great ! Thanks you so much for your help @tonyqus.
